name: Development Deploy (RSYNC over SSH)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: ${{ secrets.REMOTE_PATH_DEV }}
        remote_host: ${{ secrets.REMOTE_HOST_DEV }}
        remote_port: ${{ secrets.REMOTE_HOST_PORT_DEV }}
        remote_user: ${{ secrets.REMOTE_USER_DEV }}
        remote_key: ${{ secrets.SSH_KEY_DEV }}
